namespace DemoServer.Enums;

/// <summary>
/// Possible roles of a content block in a chat thread.
/// </summary>
public enum Role
{
    /// <summary>
    /// No role specified.
    /// </summary>
    NONE,
    
    /// <summary>
    /// Role is unknown.
    /// </summary>
    UNKNOWN,
    
    /// <summary>
    /// System role, e.g., instructions to the AI model.
    /// </summary>
    SYSTEM,
    
    /// <summary>
    /// User role, e.g., user input.
    /// </summary>
    USER,
    
    /// <summary>
    /// AI role, e.g., AI-generated response.
    /// </summary>
    AI,
    
    /// <summary>
    /// Content generated by an AI agent.
    /// </summary>
    AGENT,
}